class Project {
  final String name;
  final String description;
  final String image;
  final String link;
  Project(this.name, this.description, this.image, this.link);
}

List<Project> projectList = [
  Project(
    'FlutterChat',
    'A cross-platform chat application built using Flutter and Firebase. This app features real-time messaging, push notifications, and seamless integration with Firebase for authentication and data storage.',
    'assets/images/chat.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'KotlinWeather',
    'An Android weather app developed using Kotlin. The app fetches real-time weather data from a REST API and provides users with detailed weather forecasts, alerts, and customizable widgets.',
    'assets/images/weather.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'TaskMaster',
    'A productivity app developed using Android Studio and Firebase. TaskMaster helps users manage their daily tasks with features like task categorization, deadline reminders, and cloud sync using Firebase Firestore.',
    'assets/images/task.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'FlutterCommerce',
    'An e-commerce application built with Flutter, featuring a sleek UI, secure payment integration, and Firebase backend for managing user data, orders, and inventory in real-time.',
    'assets/images/pfp.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Youtube_DownloaderAndroid',
    'An Android-based YouTube downloader built with Flutter.',
    'assets/images/youtube_android.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'PokeDex',
    'A Flutter-based Pokédex app with API integration.',
    'assets/images/pokedex.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-AnimatedIcon',
    'Demonstrates animated icons in Flutter.',
    'assets/images/animated_icon.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Firebase_CRUD',
    'A Flutter app demonstrating CRUD operations with Firebase.',
    'assets/images/firebase_crud.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Firebase_LOGINandroid',
    'An Android Firebase authentication project using Flutter.',
    'assets/images/firebase_auth_android.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Personal_Portfolio',
    'A Flutter-based personal portfolio application.',
    'assets/images/portfolio.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-CustomErrorPage',
    'A Flutter project showcasing custom error pages.',
    'assets/images/error_page.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'AnimeUI_API',
    'A Flutter-based anime UI app with API integration.',
    'assets/images/anime.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Netflix',
    'A Netflix UI clone built with Flutter.',
    'assets/images/netflix.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'GoJek_clone',
    'A Flutter UI clone of the GoJek app.',
    'assets/images/gojek.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Spotify-Mobile',
    'A Flutter-based mobile UI inspired by Spotify.',
    'assets/images/spotify.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-GIFgetter',
    'A Flutter app for fetching and displaying GIFs.',
    'assets/images/gifgetter.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-JSONdata',
    'Demonstrates handling JSON data in Flutter.',
    'assets/images/json.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'GenshinImpactSeason3',
    'A Flutter project related to Genshin Impact (image broken).',
    'assets/images/genshin.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-AnimatedPlayPause',
    'A Flutter app with animated play/pause buttons.',
    'assets/images/playpause.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-CustomButton',
    'A Flutter project showcasing custom button designs.',
    'assets/images/button.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-AnimeList',
    'An anime list app built with Flutter.',
    'assets/images/animelist.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-CreditCard',
    'A Flutter project implementing a credit card UI.',
    'assets/images/creditcard.png',
    'https://github.com/r3nyah',
  ),
  Project(
    '3D_Carousel',
    'A Flutter project featuring a 3D carousel UI.',
    'assets/images/3d_carousel.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-AudioPlayer',
    'A Flutter app for playing audio files.',
    'assets/images/audio_player.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-MapsMarker',
    'A Flutter app showcasing Google Maps markers.',
    'assets/images/maps_marker.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-CollapsibleDrawer',
    'A Flutter app demonstrating a collapsible drawer UI.',
    'assets/images/drawer.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'GenshinImpactSeason2',
    'A Flutter project related to Genshin Impact.',
    'assets/images/genshin2.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-SlideToUnlock',
    'A Flutter app featuring a slide-to-unlock UI.',
    'assets/images/slide_unlock.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-URL_launcher',
    'A Flutter app demonstrating URL launching.',
    'assets/images/url_launcher.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-Form',
    'A Flutter project showcasing form handling.',
    'assets/images/form.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Age_calculate',
    'A Flutter app for calculating age based on birthdate.',
    'assets/images/age_calculator.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'World_Weather',
    'A Flutter app fetching real-time weather data.',
    'assets/images/weather_app.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-ChangeTheme',
    'A Flutter project demonstrating theme switching.',
    'assets/images/theme.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutte-DatePicker',
    'A Flutter project demonstrating date picking functionality.',
    'assets/images/datepicker.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Spotify',
    'A Flutter project related to Spotify UI or features.',
    'assets/images/spotify.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-AutoSlider',
    'A Flutter project demonstrating an auto slider feature.',
    'assets/images/autoslider.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-ListViewApi',
    'A Flutter project fetching and displaying API data in a ListView.',
    'assets/images/listviewapi.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Google_Logo_Animation',
    'A Flutter animation project replicating Google logo effects.',
    'assets/images/google_logo_animation.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'GenshinImpact',
    'A Flutter project related to Genshin Impact.',
    'assets/images/genshinimpact.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-DrawerMenu',
    'A Flutter project implementing a drawer menu.',
    'assets/images/drawer_menu.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-ValidatePassword',
    'A Flutter project for password validation.',
    'assets/images/validate_password.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-ToDoList-Season2',
    'A Flutter project for a to-do list application (Season 2).',
    'assets/images/todolist_s2.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-SnakeGame',
    'A Flutter project implementing a classic Snake game.',
    'assets/images/snake_game.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-Fingerprint',
    'A Flutter project demonstrating fingerprint authentication.',
    'assets/images/fingerprint.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-DrawHelper',
    'A Flutter project for drawing and sketching assistance.',
    'assets/images/draw_helper.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-Body_Mass_Index',
    'A Flutter project for BMI calculation.',
    'assets/images/bmi.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-StopWatch',
    'A Flutter project implementing a stopwatch.',
    'assets/images/stopwatch.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-AnimatedLogin',
    'A Flutter project with an animated login screen.',
    'assets/images/animated_login.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-GeneratePassword',
    'A Flutter project for generating secure passwords.',
    'assets/images/generate_password.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-PINcode',
    'A Flutter project for PIN code input and validation.',
    'assets/images/pincode.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-Calculator',
    'A Flutter project implementing a basic calculator.',
    'assets/images/calculator.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-DeviceCheck',
    'A Flutter project checking device specifications.',
    'assets/images/device_check.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-BottomNavigationBar',
    'A Flutter project demonstrating bottom navigation bar.',
    'assets/images/bottom_navbar.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-FilterSearch',
    'A Flutter project implementing search filtering.',
    'assets/images/filter_search.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-TicTacToe',
    'A Flutter project implementing Tic-Tac-Toe game.',
    'assets/images/tic_tac_toe.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-QuizApp',
    'A Flutter project for a quiz application.',
    'assets/images/quiz_app.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-Notes',
    'A Flutter project for taking and managing notes.',
    'assets/images/notes.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-ProviderFundamental',
    'A Flutter project explaining Provider state management.',
    'assets/images/provider_fundamental.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-Animation',
    'A Flutter project exploring Flutter animations.',
    'assets/images/animation.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-Coin',
    'A Flutter project related to cryptocurrency or flipping a coin.',
    'assets/images/coin.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-Bloc',
    'A Flutter project explaining Bloc state management.',
    'assets/images/bloc.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-FoodCheckout',
    'A Flutter project demonstrating a food checkout process.',
    'assets/images/food_checkout.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-InstaClone',
    'A Flutter project replicating Instagram UI.',
    'assets/images/insta_clone.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-ToDoList',
    'A Flutter project for a simple to-do list application.',
    'assets/images/todolist.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-SimpleApp',
    'A Flutter project demonstrating basic app structure.',
    'assets/images/simple_app.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-RestfulAPI',
    'A Flutter project demonstrating RESTful API integration.',
    'assets/images/restful_api.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-CRUD',
    'A Flutter project implementing CRUD operations.',
    'assets/images/crud.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-Firebase',
    'A Flutter project integrating Firebase services.',
    'assets/images/firebase.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-SendData',
    'A Flutter project demonstrating data sending between screens.',
    'assets/images/send_data.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-FetchData',
    'A Flutter project demonstrating data fetching.',
    'assets/images/fetch_data.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-NavigateScreen',
    'A Flutter project explaining screen navigation.',
    'assets/images/navigate_screen.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-Animations',
    'A Flutter project demonstrating various animations.',
    'assets/images/flutter_animations.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-Login',
    'A Flutter project implementing a login screen.',
    'assets/images/login.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-RecipeSearch',
    'A Flutter project for searching recipes.',
    'assets/images/recipe_search.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Flutter-RecipeList',
    'A Flutter project displaying a list of recipes.',
    'assets/images/recipe_list.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'World_Time',
    'A Flutter project displaying world time data.',
    'assets/images/world_time.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Fundamental',
    'A Flutter project covering fundamental concepts.',
    'assets/images/fundamental.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'Quotes',
    'A Flutter project displaying inspirational quotes.',
    'assets/images/quotes.png',
    'https://github.com/r3nyah',
  ),
  Project(
    'ID-card',
    'A Flutter project for generating ID cards.',
    'assets/images/id_card.png',
    'https://github.com/r3nyah',
  ),
];
